### ISSUE TITLE
build electron issues unix 

### ISSUE THREAD

**Issue by iddoeldor** [signalapp/ringrtc#13]
```
$ bash -x bin/build-electron
+ set -e
+++ dirname bin/build-electron
++ realpath -e bin
+ BIN_DIR=/tmp/ringrtc/bin
+ . /tmp/ringrtc/bin/env.sh
++ '[' -d /tmp/ringrtc/bin ']'
+++ dirname /tmp/ringrtc/bin
++ PROJECT_DIR=/tmp/ringrtc
++ CONFIG_DIR=/tmp/ringrtc/config
++ PATCH_DIR=/tmp/ringrtc/patches/webrtc
++ RINGRTC_SRC_DIR=/tmp/ringrtc/src
++ OUTPUT_DIR=/tmp/ringrtc/out
++ PUBLISH_DIR=/tmp/ringrtc/publish
++ PATCH_HASH=/tmp/ringrtc/out/patch-hash
++ WEBRTC_DIR=/tmp/ringrtc/src/webrtc
++ WEBRTC_SRC_DIR=/tmp/ringrtc/src/webrtc/src
++ RINGRTC_WEBRTC_SRC_DIR=/tmp/ringrtc/src/webrtc/src/ringrtc
++ VERSION_INFO=/tmp/ringrtc/config/version.sh
++ '[' -f /tmp/ringrtc/config/version.sh ']'
++ . /tmp/ringrtc/config/version.sh
+++ WEBRTC_VERSION=4183
+++ RINGRTC_MAJOR_VERSION=2
+++ RINGRTC_MINOR_VERSION=7
+++ RINGRTC_REVISION=0
+++ RINGRTC_VERSION=2.7.0
+++ PROJECT_VERSION=2.7.0
++ '[' -f /tmp/ringrtc/out/webrtc-version.env ']'
++ WEBRTC_REVISION=branch-heads/4183
++ INTENDED_WEBRTC_PLATFORM=
++ '[' -f /tmp/ringrtc/out/platform.env ']'
++ '[' -n '' ']'
+ BUILD_TYPE=debug
+ '[' '' '!=' '' ']'
++ get_default_platform
++ hash rustup
++ case "$(rustup show active-toolchain)" in
+++ rustup show active-toolchain
++ echo linux
+ DEFAULT_PLATFORM=linux
+ '[' linux = unknown ']'
+ export MACOSX_DEPLOYMENT_TARGET=10.10
+ MACOSX_DEPLOYMENT_TARGET=10.10
+ cd src/rust/src/webrtc
+ '[' debug = debug ']'
+ gn gen -C out/Debug '--args=use_custom_libcxx=false rtc_build_examples=false rtc_build_tools=false rtc_include_tests=false rt
c_enable_protobuf=false rtc_use_x11=false'
ERROR Can't find source root.
I could not find a ".gn" file in the current directory or any parent,
and the --root command-line argument was not specified.

```

**Comment by jim-signal** [comment]
Hi, after the fix for issue https://github.com/signalapp/ringrtc/issues/14, and after you run this again:

`./bin/prepare-workspace unix`

Can you get beyond this? I am assuming you are building for linux (the unix platform here).

**Comment by iddoeldor** [comment]
```sh
15:36:58 /tmp/ringrtc$ git diff
diff --git a/config/webrtc.gclient.common b/config/webrtc.gclient.common
index efa6592..df42a5c 100644
--- a/config/webrtc.gclient.common
+++ b/config/webrtc.gclient.common
@@ -7,7 +7,7 @@

 solutions = [
   { "name"        : "src",
-    "url"         : "git@github.com:signalapp/webrtc.git",
+    "url"         : "https://github.com/signalapp/webrtc.git",
     "deps_file"   : "DEPS",
   },
 ]
15:37:02 /tmp/ringrtc$ ./bin/prepare-workspace unix
Downloading WebRTC dependencies to /tmp/ringrtc/src/webrtc from version 4183a
Syncing projects: 100% (307/307), done.
Running hooks: 100% (22/22), done.
Preparing workspace for Unix...
15:37:27 /tmp/ringrtc$ make electron
# TODO ./bin/prepare-workspace
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /tmp/ringrtc/src/webrtc/src/out/Debug/
Command: python /tmp/ringrtc/src/webrtc/src/build/config/linux/pkg-config.py -s /tmp/ringrtc/src/webrtc/src/build/linux/debian_
sid_amd64-sysroot -a x64 gio-2.0 gio-unix-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/tmp/ringrtc/src/webrtc/src/build/config/linux/pkg-config.py", line 248, in <module>
    sys.exit(main())
  File "/tmp/ringrtc/src/webrtc/src/build/config/linux/pkg-config.py", line 143, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "/tmp/ringrtc/src/webrtc/src/build/config/linux/pkg-config.py", line 82, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ).decode('utf-8')
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //modules/desktop_capture/BUILD.gn:191:5: whence it was called.
    pkg_config("gio") {
    ^------------------
See //modules/BUILD.gn:28:15: which caused the file to be included.
    deps += [ "desktop_capture" ]
              ^----------------
Makefile:59: recipe for target 'electron' failed
make: *** [electron] Error 1
```

**Comment by iddoeldor** [comment]
Trying something, will update
```
sudo apt-get update && sudo apt-get install pkg-config
```

**Comment by jim-signal** [comment]
We added a task to update the Makefile to prepare the workspace for electron builds. No estimate though for that.

What version of Ubuntu are you using? On Ubuntu Desktop 18.04/20.04, pkg-config seems to already be there. If there is an exception to that, we would prefer to update the documentation.

**Comment by iddoeldor** [comment]
Ubuntu 18.04

It seems that when I replace the `libringrtc.node` @ `/opt/Signal/` it doen't work

**Comment by jim-signal** [comment]
It probably won't work if different versions are used as internal interfaces change, etc. If you are running the production version of the Signal Desktop client (1.36.1), you would need to build RingRTC v2.5.2. I think it also applies to the latest beta.

You shouldn't need to download the whole WebRTC again, so hopefully the build is faster this time.

**Comment by iddoeldor** [comment]
Great, and for beta ? 

How do I know which version to use ?

**Comment by jim-signal** [comment]
You can go to the link you provided, go back to the repo main page for that branch, and look at the commits. You should see what the most recent message like "Update to RingRTC v2.5.2" is. Or, on the line you referenced, go to https://github.com/signalapp/signal-ringrtc-node.git and find that specific commit.

**Comment by iddoeldor** [comment]
```sh
/tmp/ringrtc$ git checkout -b v_2_5_2 9c04405dd09d796401441edb7192bab31ae8337f
Switched to a new branch 'v_2_5_2'
/tmp/ringrtc$ git status
On branch v_2_5_2
nothing to commit, working tree clean
/tmp/ringrtc$ vi CHANGELOG.md
/tmp/ringrtc$ make electron
# TODO ./bin/prepare-workspace
Done. Made 806 targets from 225 files in 192ms
ninja: Entering directory `out/Debug'
[1/6] CXX obj/ringrtc/ringrtc/media.o
FAILED: obj/ringrtc/ringrtc/media.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ringrtc/ringrtc/media.o.d -DENABLE_RINGRTC -DUSE_UDEV -DU
SE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SO
URCE -DCR_CLANG_REVISION=\"n356235-f7f1abdb-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCR_SYSROOT_HASH=d6879d611f3dc
f3da8dd92e080029394aa30bc42 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWEBRTC_ENABLE_PROTOBUF=0 -DWEBRTC_INCLUDE_INTERNAL_AUDIO
_DEVICE -DRTC_ENABLE_VP9 -DHAVE_SCTP -DWEBRTC_LIBRARY_IMPL -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_POSIX -DWEBRTC_L
INUX -DABSL_ALLOCATOR_NOTHROW=1 -I../../ringrtc -I../.. -Igen -I../../third_party/abseil-cpp -I../../third_party/libyuv/include
 -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-al
l-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -m64
 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang .
-no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missin
g-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template
-Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-ali
gnment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -O0 -fno-omit-frame-pointer -g2 -Xclang -debug-info-kin
d=constructor -gsplit-dwarf -ggnu-pubnames -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conver
sion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -Wc++11-narrowing -Wimplicit-fallthrough -Wth
read-safety -Winconsistent-missing-override -Wundef -Wunused-lambda-capture -Wno-shorten-64-to-32 -Wno-undefined-bool-conversio
n -Wno-tautological-undefined-compare -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti --sysroot=../../build/
linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -Wnon-virtual-dtor -Woverloaded-virtual -c ../../ringrtc/rffi/src/me
dia.cc -o obj/ringrtc/ringrtc/media.o
../../ringrtc/rffi/src/media.cc:29:22: error: no matching constructor for initialization of 'webrtc::VideoFrameMetadata'
  VideoFrameMetadata metadata = {};
                     ^          ~~
../../api/video/video_frame_metadata.h:29:12: note: candidate constructor not viable: requires single argument 'header', but no
 arguments were provided
  explicit VideoFrameMetadata(const RTPVideoHeader& header);
           ^
../../api/video/video_frame_metadata.h:30:3: note: candidate constructor not viable: requires 1 argument, but 0 were provided
  VideoFrameMetadata(const VideoFrameMetadata&) = default;
  ^
../../ringrtc/rffi/src/media.cc:30:12: error: no member named 'width' in 'webrtc::VideoFrameMetadata'; did you mean 'width_'?
  metadata.width = frame.width();
           ^~~~~
           width_
../../api/video/video_frame_metadata.h:49:11: note: 'width_' declared here
  int16_t width_;
          ^
../../ringrtc/rffi/src/media.cc:31:12: error: no member named 'height' in 'webrtc::VideoFrameMetadata'; did you mean 'height_'?
  metadata.height = frame.height();
           ^~~~~~
           height_
../../api/video/video_frame_metadata.h:50:11: note: 'height_' declared here
  int16_t height_;
          ^
../../ringrtc/rffi/src/media.cc:32:12: error: no member named 'rotation' in 'webrtc::VideoFrameMetadata'
  metadata.rotation = frame.rotation();
  ~~~~~~~~ ^
../../ringrtc/rffi/src/media.cc:40:17: error: no member named 'rotation' in 'webrtc::VideoFrameMetadata'
  if ((metadata.rotation == kVideoRotation_90) || (metadata.rotation == kVideoRotation_270)) {
       ~~~~~~~~ ^
../../ringrtc/rffi/src/media.cc:40:61: error: no member named 'rotation' in 'webrtc::VideoFrameMetadata'
  if ((metadata.rotation == kVideoRotation_90) || (metadata.rotation == kVideoRotation_270)) {
                                                   ~~~~~~~~ ^
../../ringrtc/rffi/src/media.cc:41:14: error: no member named 'width' in 'webrtc::VideoFrameMetadata'; did you mean 'width_'?
    metadata.width = frame.height();
             ^~~~~
             width_
../../api/video/video_frame_metadata.h:49:11: note: 'width_' declared here
  int16_t width_;
          ^
../../ringrtc/rffi/src/media.cc:42:14: error: no member named 'height' in 'webrtc::VideoFrameMetadata'; did you mean 'height_'?
    metadata.height = frame.width();
             ^~~~~~
             height_
../../api/video/video_frame_metadata.h:50:11: note: 'height_' declared here
  int16_t height_;
          ^
../../ringrtc/rffi/src/media.cc:44:12: error: no member named 'rotation' in 'webrtc::VideoFrameMetadata'
  metadata.rotation = kVideoRotation_0;
  ~~~~~~~~ ^
../../ringrtc/rffi/src/media.cc:45:27: error: no viable conversion from 'webrtc::VideoFrameMetadata' to 'VideoFrameMetadata'
  cbs_.onVideoFrame(obj_, metadata, buffer);
                          ^~~~~~~~
../../ringrtc/rffi/api/media.h:18:9: note: candidate constructor (the implicit copy constructor) not viable: no known conversio
n from 'webrtc::VideoFrameMetadata' to 'const VideoFrameMetadata &' for 1st argument
typedef struct {
        ^
../../ringrtc/rffi/api/media.h:18:9: note: candidate constructor (the implicit move constructor) not viable: no known conversio
n from 'webrtc::VideoFrameMetadata' to 'VideoFrameMetadata &&' for 1st argument
10 errors generated.
[3/6] CXX obj/ringrtc/ringrtc/peer_connection_factory.o
ninja: build stopped: subcommand failed.
Makefile:59: recipe for target 'electron' failed
make: *** [electron] Error 1
```

**Comment by iddoeldor** [comment]
It worked after rebuilding WebRTC, I will summarize & update the docs.
